"""
Migration Report Generator.
"""

import json
from datetime import datetime
from typing import Optional
from pathlib import Path
from dataclasses import dataclass

from .migrator import MigrationReport, MigrationIssue


@dataclass
class ReportConfig:
    format: str = "html"
    include_patches: bool = True
    title: str = "CUDA -> ROCm Migration Report"


def _escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


class ReportGenerator:
    def __init__(self, config: Optional[ReportConfig] = None):
        self.config = config or ReportConfig()

    def generate(self, report: MigrationReport, output_path: str):
        if self.config.format == "json":
            self._generate_json(report, output_path)
        else:
            self._generate_html(report, output_path)

    def _generate_json(self, report: MigrationReport, output_path: str):
        data = {
            "meta": {"tool": "pytorch-rocm-check", "generated_at": datetime.now().isoformat(),
                     "project": report.project_path},
            "summary": report.summary,
            "issues": [{"file": i.file, "line": i.line, "severity": i.severity,
                        "description": i.description, "suggested_fix": i.suggested_fix}
                       for i in report.issues],
        }
        Path(output_path).write_text(json.dumps(data, indent=2))

    def _generate_html(self, report: MigrationReport, output_path: str):
        issues_html = ""
        for issue in report.issues:
            icon = {"error": "X", "warning": "!", "info": "i"}.get(issue.severity, "?")
            issues_html += f"<div class='issue'><b>[{icon}]</b> {issue.file}:{issue.line} - {_escape(issue.description)}</div>\n"

        html = f"""<!DOCTYPE html><html><head><title>{self.config.title}</title></head><body>
<h1>{self.config.title}</h1>
<p>Project: {_escape(report.project_path)} | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
<p>Files: {report.files_scanned} | Issues: {report.summary.get('total_issues', 0)}</p>
{issues_html if issues_html else '<p>No issues found.</p>'}
<p><i>Generated by pytorch-rocm-check | MIT License</i></p>
</body></html>"""
        Path(output_path).write_text(html)


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=str)
    parser.add_argument("--output", default="migration-report.html")
    parser.add_argument("--format", choices=["html", "json"], default="html")
    args = parser.parse_args()

    with open(args.input) as f:
        data = json.load(f)

    report = MigrationReport(project_path=data["meta"]["project"])
    report.files_scanned = data["summary"]["files_scanned"]
    report.issues = [MigrationIssue(**i) for i in data["issues"]]

    gen = ReportGenerator(ReportConfig(format=args.format))
    gen.generate(report, args.output)
    print(f"Report generated: {args.output}")


if __name__ == "__main__":
    main()
